[project]
name = "wiki-chat"
description = "wiki chat-bot"
version = "0.1.0"

requires-python = ">=3.12"
dependencies = [
    "llama-index",
    "llama-index-llms-ollama",
    "fastapi[standard]",
    "wikipedia-api"
]